# Generated by Django 3.1.4 on 2021-03-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
