# Generated by Django 3.1.4 on 2021-03-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
